
--  EX30:

Insert into PERMISOS (EPEPER,EPENOM,EPELUC,EPECOM,EPECAP,EPEFCO,EPEFEX,EPERES,EPEVAL,EPEGRP,EPETIP,EPEFLAGS,EPEVIA,EPEMVA,EPEREG,EPECARTASMTAS,EPENOMBRESEDE,EXCLUDESEDE) values ('DT5','RESIDENCIA TEMPORAL POR CIRCUNSTANCIAS EXCEPCIONALES DE LA DT 5ª','S',' ','N',' ',' ','S','S','PER','RE','SSNCNNNSNNNNSNN','EES','12','RD1155','N',null,'N');

update VIA_ACCESO set evides='ARRAIGO DE SEGUNDA OPORTUNIDAD INICIAL (ART. 127.A Y DT5)' where evicod='SO1';
update VIA_ACCESO set evides='ARRAIGO SOCIOLABORAL INICIAL (ART. 127.B Y DT5)' where evicod='SL1';
update VIA_ACCESO set evides='ARRAIGO SOCIAL INICIAL (ART. 127.C Y DT5)' where evicod='SC1';
update VIA_ACCESO set evides='ARRAIGO SOCIOFORMATIVO INICIAL (127.D Y DT5)' where evicod='SF1';

Insert into AUTORIZAC (AUTCOD,AUTDES,AUTFLAGS,AUTVAL,AUTGRP,AUTCLA,AUTMOD,AUTTIP,AUTDES_CAT,AUTDES_CAT_CAS,AUTDES_UMI,AUTJERAR,AUTCLAS) values ('E0T500','RESIDENCIA TEMPORAL POR CIRCUNSTANCIAS EXCEPCIONALES DE LA DT 5ª - ARRAIGO DE SEGUNDA OPORTUNIDAD INICIAL (ART. 127.A Y DT5)',null,'S',null,null,null,null,null,null,null,null,null);
Insert into AUTORIZAC (AUTCOD,AUTDES,AUTFLAGS,AUTVAL,AUTGRP,AUTCLA,AUTMOD,AUTTIP,AUTDES_CAT,AUTDES_CAT_CAS,AUTDES_UMI,AUTJERAR,AUTCLAS) values ('E0T501','RESIDENCIA TEMPORAL POR CIRCUNSTANCIAS EXCEPCIONALES DE LA DT 5ª - ARRAIGO SOCIOLABORAL INICIAL (ART. 127.B Y DT5)',null,'S',null,null,null,null,null,null,null,null,null);
Insert into AUTORIZAC (AUTCOD,AUTDES,AUTFLAGS,AUTVAL,AUTGRP,AUTCLA,AUTMOD,AUTTIP,AUTDES_CAT,AUTDES_CAT_CAS,AUTDES_UMI,AUTJERAR,AUTCLAS) values ('E0T502','RESIDENCIA TEMPORAL POR CIRCUNSTANCIAS EXCEPCIONALES DE LA DT 5ª - ARRAIGO SOCIAL INICIAL (ART. 127.C Y DT5)',null,'S',null,null,null,null,null,null,null,null,null);
Insert into AUTORIZAC (AUTCOD,AUTDES,AUTFLAGS,AUTVAL,AUTGRP,AUTCLA,AUTMOD,AUTTIP,AUTDES_CAT,AUTDES_CAT_CAS,AUTDES_UMI,AUTJERAR,AUTCLAS) values ('E0T503','RESIDENCIA TEMPORAL POR CIRCUNSTANCIAS EXCEPCIONALES DE LA DT 5ª - ARRAIGO SOCIOFORMATIVO INICIAL (127.D Y DT5)',null,'S',null,null,null,null,null,null,null,null,null);

Insert into EXTRANGN.VIA_PERMISO (EVPPER,EVPVIA,EVPFLAGS,EVPVAL,EVPMTAS,EVPFECINI,EVPFECFIN,EVPFORMULARIO,EVPESCCOS,EVPFGR,EVPVERRES,CODIGO_SIA,IGUALDAD,EVPDGPTJ,EVPETIQUETAFAM,EVPPROMOTOR,EVPTRANSFRONTERIZO,EVPFAMILIAR,EVPNACIONALIDAD,EVPNIVELESTUDIOS,EVPCENTROESTUDIOS,EVPAMBITO,EVPVISADODESCESP,EVPRECUPERALD,EVPIGUALDAD,EVPTIPOTITULAR,EVPRESSINPAGTASR,EVPNSOPORTEUE,EVPCNED,EVPADJDOCRESUELTO,EVPPERMANENTE,EVPNUMPLAZO,EVPTIPPLAZO,EVPTIPESTIMACION,EVPLEYENDA,EVPINITASAS) values ('DT5','SO1','S12LNASSNNNNNNCDNNSNN O S              A','S','E0T500',to_date('20/05/25','DD/MM/RR'),null,'EX30','S',to_date('11/04/25','DD/MM/RR'),'S','201321','N','S','F','N','N','N',null,'N','N',null,'N','N','N','G','E','N','N','N','S','3','M','D','N','S');
Insert into EXTRANGN.VIA_PERMISO (EVPPER,EVPVIA,EVPFLAGS,EVPVAL,EVPMTAS,EVPFECINI,EVPFECFIN,EVPFORMULARIO,EVPESCCOS,EVPFGR,EVPVERRES,CODIGO_SIA,IGUALDAD,EVPDGPTJ,EVPETIQUETAFAM,EVPPROMOTOR,EVPTRANSFRONTERIZO,EVPFAMILIAR,EVPNACIONALIDAD,EVPNIVELESTUDIOS,EVPCENTROESTUDIOS,EVPAMBITO,EVPVISADODESCESP,EVPRECUPERALD,EVPIGUALDAD,EVPTIPOTITULAR,EVPRESSINPAGTASR,EVPNSOPORTEUE,EVPCNED,EVPADJDOCRESUELTO,EVPPERMANENTE,EVPNUMPLAZO,EVPTIPPLAZO,EVPTIPESTIMACION,EVPLEYENDA,EVPINITASAS) values ('DT5','SL1','S12LNASSNNNNNNCDNNSNN O S              A','S','E0T501',to_date('20/05/25','DD/MM/RR'),null,'EX30','S',to_date('11/04/25','DD/MM/RR'),'S','201321','N','S','F','N','N','N',null,'N','N',null,'N','N','N','G','E','N','N','N','S','3','M','D','N','S');
Insert into EXTRANGN.VIA_PERMISO (EVPPER,EVPVIA,EVPFLAGS,EVPVAL,EVPMTAS,EVPFECINI,EVPFECFIN,EVPFORMULARIO,EVPESCCOS,EVPFGR,EVPVERRES,CODIGO_SIA,IGUALDAD,EVPDGPTJ,EVPETIQUETAFAM,EVPPROMOTOR,EVPTRANSFRONTERIZO,EVPFAMILIAR,EVPNACIONALIDAD,EVPNIVELESTUDIOS,EVPCENTROESTUDIOS,EVPAMBITO,EVPVISADODESCESP,EVPRECUPERALD,EVPIGUALDAD,EVPTIPOTITULAR,EVPRESSINPAGTASR,EVPNSOPORTEUE,EVPCNED,EVPADJDOCRESUELTO,EVPPERMANENTE,EVPNUMPLAZO,EVPTIPPLAZO,EVPTIPESTIMACION,EVPLEYENDA,EVPINITASAS) values ('DT5','SC1','S12LNASSNNNNNNCDNNSNN O S              A','S','E0T502',to_date('20/05/25','DD/MM/RR'),null,'EX30','S',to_date('11/04/25','DD/MM/RR'),'S','201321','N','S','F','N','N','N',null,'N','N',null,'N','N','N','G','E','N','N','N','S','3','M','D','N','S');
Insert into EXTRANGN.VIA_PERMISO (EVPPER,EVPVIA,EVPFLAGS,EVPVAL,EVPMTAS,EVPFECINI,EVPFECFIN,EVPFORMULARIO,EVPESCCOS,EVPFGR,EVPVERRES,CODIGO_SIA,IGUALDAD,EVPDGPTJ,EVPETIQUETAFAM,EVPPROMOTOR,EVPTRANSFRONTERIZO,EVPFAMILIAR,EVPNACIONALIDAD,EVPNIVELESTUDIOS,EVPCENTROESTUDIOS,EVPAMBITO,EVPVISADODESCESP,EVPRECUPERALD,EVPIGUALDAD,EVPTIPOTITULAR,EVPRESSINPAGTASR,EVPNSOPORTEUE,EVPCNED,EVPADJDOCRESUELTO,EVPPERMANENTE,EVPNUMPLAZO,EVPTIPPLAZO,EVPTIPESTIMACION,EVPLEYENDA,EVPINITASAS) values ('DT5','SF1','N12DNNNSNNNNNNNNNNNNN OMS          N NND','S','E0T503',to_date('20/05/25','DD/MM/RR'),null,'EX30','S',to_date('11/04/25','DD/MM/RR'),'S','201321','N','S','F','N','N','N',null,'N','N',null,'N','N','N','G','N','N','S','S','S','3','M','D','N','N');

Insert into CONFIGURACION_AUTORIZACIONES (ID_CFG_AUTORIZACIONES,TIPO_COMPETENCIA,COD_PERMISO,COD_VIA,ALTA_EXPEDIENTES,MOD_EXPEDIENTES,RES_EXPEDIENTE,RES_PROPUESTA_AGE,RES_PROPUESTA_CCAA,GEN_TASAS_TRABAJO,GEN_TASAS_RESIDENCIA,POR_DEFECTO) values (SQ_CONF_AUTORIZACIONES.NEXTVAL,'00002','DT5','SO1','S','S','S','N','N','S','S','N');
Insert into CONFIGURACION_AUTORIZACIONES (ID_CFG_AUTORIZACIONES,TIPO_COMPETENCIA,COD_PERMISO,COD_VIA,ALTA_EXPEDIENTES,MOD_EXPEDIENTES,RES_EXPEDIENTE,RES_PROPUESTA_AGE,RES_PROPUESTA_CCAA,GEN_TASAS_TRABAJO,GEN_TASAS_RESIDENCIA,POR_DEFECTO) values (SQ_CONF_AUTORIZACIONES.NEXTVAL,'00002','DT5','SL1','S','S','S','N','N','S','S','N');
Insert into CONFIGURACION_AUTORIZACIONES (ID_CFG_AUTORIZACIONES,TIPO_COMPETENCIA,COD_PERMISO,COD_VIA,ALTA_EXPEDIENTES,MOD_EXPEDIENTES,RES_EXPEDIENTE,RES_PROPUESTA_AGE,RES_PROPUESTA_CCAA,GEN_TASAS_TRABAJO,GEN_TASAS_RESIDENCIA,POR_DEFECTO) values (SQ_CONF_AUTORIZACIONES.NEXTVAL,'00002','DT5','SC1','S','S','S','N','N','S','S','N');
Insert into CONFIGURACION_AUTORIZACIONES (ID_CFG_AUTORIZACIONES,TIPO_COMPETENCIA,COD_PERMISO,COD_VIA,ALTA_EXPEDIENTES,MOD_EXPEDIENTES,RES_EXPEDIENTE,RES_PROPUESTA_AGE,RES_PROPUESTA_CCAA,GEN_TASAS_TRABAJO,GEN_TASAS_RESIDENCIA,POR_DEFECTO) values (SQ_CONF_AUTORIZACIONES.NEXTVAL,'00002','DT5','SF1','S','S','S','N','N','S','S','N');
Insert into CONFIGURACION_AUTORIZACIONES (ID_CFG_AUTORIZACIONES,TIPO_COMPETENCIA,COD_PERMISO,COD_VIA,ALTA_EXPEDIENTES,MOD_EXPEDIENTES,RES_EXPEDIENTE,RES_PROPUESTA_AGE,RES_PROPUESTA_CCAA,GEN_TASAS_TRABAJO,GEN_TASAS_RESIDENCIA,POR_DEFECTO) values (SQ_CONF_AUTORIZACIONES.NEXTVAL,'00003','DT5','SO1','S','S','S','N','N','S','S','N');
Insert into CONFIGURACION_AUTORIZACIONES (ID_CFG_AUTORIZACIONES,TIPO_COMPETENCIA,COD_PERMISO,COD_VIA,ALTA_EXPEDIENTES,MOD_EXPEDIENTES,RES_EXPEDIENTE,RES_PROPUESTA_AGE,RES_PROPUESTA_CCAA,GEN_TASAS_TRABAJO,GEN_TASAS_RESIDENCIA,POR_DEFECTO) values (SQ_CONF_AUTORIZACIONES.NEXTVAL,'00003','DT5','SL1','S','S','S','N','N','S','S','N');
Insert into CONFIGURACION_AUTORIZACIONES (ID_CFG_AUTORIZACIONES,TIPO_COMPETENCIA,COD_PERMISO,COD_VIA,ALTA_EXPEDIENTES,MOD_EXPEDIENTES,RES_EXPEDIENTE,RES_PROPUESTA_AGE,RES_PROPUESTA_CCAA,GEN_TASAS_TRABAJO,GEN_TASAS_RESIDENCIA,POR_DEFECTO) values (SQ_CONF_AUTORIZACIONES.NEXTVAL,'00003','DT5','SC1','S','S','S','N','N','S','S','N');
Insert into CONFIGURACION_AUTORIZACIONES (ID_CFG_AUTORIZACIONES,TIPO_COMPETENCIA,COD_PERMISO,COD_VIA,ALTA_EXPEDIENTES,MOD_EXPEDIENTES,RES_EXPEDIENTE,RES_PROPUESTA_AGE,RES_PROPUESTA_CCAA,GEN_TASAS_TRABAJO,GEN_TASAS_RESIDENCIA,POR_DEFECTO) values (SQ_CONF_AUTORIZACIONES.NEXTVAL,'00003','DT5','SF1','S','S','S','N','N','S','S','N');

commit;


UPDATE VIA_PERMISO SET EVPCNED = 'N' WHERE EVPPER='DT5' AND EVPVIA='SF1';
commit;


RGI	RFI




'RGI','RGI','RFV','RFV','RIT','RIT','RIT','RIT','RIT','RIT','RIT','RGR','TRG','TRG'
